config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  # Root Route
  root 'chatroom#index'

  # Signup routes
  get '/signup', to: 'users#new'

  # User create route
  post '/signup', to: 'users#create'

  # login routes
  get '/login', to: 'sessions#new'

  # create a new session
  post '/login', to: 'sessions#create'

  # logout
  delete '/logout', to: 'sessions#destroy'

  # messages 
  post "/message", to: "messages#create"

  # ActionCable
  mount ActionCable.server, at: '/cable'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/message.rb
class Message < ApplicationRecord
    # validations
    validates :body, presence: true
    validates :user_id, presence: true
    
    # associations
    belongs_to :user

    # scopes => Scopes are custom queries that can be defined inside a model to be used in controllers and views to keep the code DRY (Don't Repeat Yourself)
    scope :custom_messages, -> { order(:created_at).last(20) }

end

app/models/user.rb
class User < ApplicationRecord
    # valiidations
    validates :username, presence: true, uniqueness: { case_sensitive: false }, length: { minimum: 3, maximum: 25 }
    validates :password, presence: true, length: { minimum: 6, maximum: 25 }

    # Password validations
    has_secure_password

    # associations
    has_many :messages
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  helper_method :current_user, :logged_in? # helper_method makes these methods available to the views
        
    def current_user
        @current_user ||= User.find(session[:user_id]) if session[:user_id] # ||= means if @current_user is nil, then execute the code on the right otherwise do nothing
    end
    
    def logged_in?
        !!current_user # !! turns current_user into a boolean
    end

    def require_user
        if !logged_in?
            flash[:negative] = "You must be logged in to perform that action."
            redirect_to login_path
        end
    end
end

app/controllers/chatroom_controller.rb
class ChatroomController < ApplicationController
    def index
        if logged_in?
            @message = Message.new
            @messages = Message.custom_messages
        else
            flash[:negative] = "You must be logged in to perform that action."
            redirect_to login_path
        end
    end

end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
    before_action :require_user

    def create
        # debugger
        message = current_user.messages.build(message_params)
        result = message.save
        if result
            # ActionCable.server.broadcast "chatroom_channel", foo: message.body 
            ActionCable.server.broadcast "chatroom_channel", mod_message: message_render(message)
        end
    end

    private
    def message_params
        params.require(:message).permit(:body)
    end

    def message_render(message)
        render(partial: 'message', locals: {message: message})
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
    before_action :logged_in_redirect, only: [:new, :create]

    def new
    end

    def create
        # debugger
        # find the user by their username
        user = User.find_by(username: params[:session][:username])

        if user && user.authenticate(params[:session][:password])
            # if the user is found and authenticated, log them in
            session[:user_id] = user.id
            flash[:success] = "You have successfully logged in!"
            redirect_to root_path
        else
            # if the user is not found or authenticated, redirect to login page
            flash.now[:negative] = "There was something wrong with your login details"
            render(:new, status: :unprocessable_entity, locals: { user: user }) 
        end
    end

    def destroy
        # log the user out
        session[:user_id] = nil
        flash[:success] = "You have successfully logged out!"
        redirect_to login_path
    end

    private

    def logged_in_redirect
        if logged_in?
            flash[:negative] = "You are already logged in."
            redirect_to root_path
        end
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    before_action :logged_in_redirect, only: [:new, :create]
    
    def new
        @user = User.new
    end
    
    def create
        # debugger
        @user = User.new(user_params)
        result = @user.save
        if result
            flash[:success] = "Welcome to the Alpha Blog, #{user_params[:username]}!, you have successfully signed up."
            session[:user_id] = @user.id
            redirect_to root_path
            # debugger
        else
            return render(:new, status: :unprocessable_entity, locals: { user: @user })
        end
    end

    private
    def user_params
        params.require(:user).permit(:username, :email, :password)
    end

    def logged_in_redirect
        if logged_in?
            flash[:negative] = "You are already logged in."
            redirect_to root_path
        end
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/chatroom/index.html.erb
<h4 class="ui center aligned icon header">
  <i class="circular rocketchat icon blue"></i>
  <div class="content">
    Message Me Chat App
    <div class="sub header">Chatroom</div>
  </div>
</h4>
<div class="ui two column grid" >
  <div class="twelve wide column">
    <div class="ui fluid raised card chatbox">
      <div class="content" id="msg-container-parent">
        <div class="ui feed" id="msg-container">
          <%= render @messages %>
        </div>
      </div>
      <div class="extra content">
        <%= form_for(@message, html: {class: "ui form reply", role:"form"}, url:message_path, remote: true) do |f| %>
          <div class="field">
            <div class="ui fluid icon input">
            <%= f.text_field :body, class: "my-input", id: "my_input", placeholder: "Type your message here..." %>
            <%= f.button '<i class="send icon"></i>'.html_safe %>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </div>
  <div class="four wide column">
    <div class="ui fluid raised card chatbox">
      <div class="content">
        <div class="ui inverted vertical menu">
          <a class="active item">
            Home
          </a>
          <a class="item">
            Messages
          </a>
          <a class="item">
            Friends
          </a>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/layouts/_alerts.html.erb
<%# Flash Message %>
<% flash.each do |name, msg|
%>
  <div class="ui container">
    <div class="ui <%= name %> message transition">
      <i class="close icon" id="close"></i>
      <div class="header">
        <%= msg%>
      </div>
    </div>
  </div>
<% end %>

app/views/layouts/_navbar.html.erb
<div class="ui inverted menu large">
  <div class="ui container">
    <a href="#" class="header item">
      Message Me Chat App
    </a>
    <a href="#" class="item"><i class="home icon"></i>Home</a>
    <a href="/" class="item"><i class="chat icon"></i> Chatroom</a>
    <%# <div class="ui simple dropdown item">
      Dropdown <i class="dropdown icon"></i>
      <div class="menu">
        <a class="item" href="#">Link Item</a>
        <a class="item" href="#">Link Item</a>
        <div class="divider"></div>
        <div class="header">Header Item</div>
        <div class="item">
          <i class="dropdown icon"></i>
          Sub Menu
          <div class="menu">
            <a class="item" href="#">Link Item</a>
            <a class="item" href="#">Link Item</a>
          </div>
        </div>
        <a class="item" href="#">Link Item</a>
      </div>
    </div> %>
    <div class="right menu">
      <% if logged_in? %>
        <div class="item">
          <a class="ui basic blue button" href="#"><i class="user icon"></i> <%= current_user.username %></a>
        </div>
        <div class="item">
        <%= button_to "Log out", logout_path, method: :delete, class: "ui basic teal button" %>
        </div>
      <% else %>
        <div class="item">
          <a class="ui basic teal button" href="/login"><i class="sign in icon"></i>Log in</a>
        </div>
        <div class="item">
          <a class="ui basic blue button" href="/signup"><i class="add user icon"></i>Sign up</a>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Test1</title>
    <%= favicon_link_tag %>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <%= render "layouts/navbar" %>
    <%= render "layouts/alerts" %>
    <div class="ui container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/messages/_message.html.erb
<div class="event">
  <div class="content">
    <div class="summary">
      <span class="user-span">
        <%= message.user.username %>
      </span>: <%= message.body %>
    </div>
  </div>
</div>

app/views/shared/_errors.html.erb
<%# flash messages %>

<%# <%
    debugger
  %> 
<% if data.errors.any? %>
    <div class="ui container">
        <div class="ui error message">
            <i class="close icon"></i>
            <div class="header">
                <%= pluralize(data.errors.count, "error") %> prohibited
                this <%= data.class.name.downcase %> from being saved:
            </div>
            <ul class="list">
                <% data.errors.full_messages.each do |msg| %>
                    <li><%= msg %></li>
                <% end %>
            </ul>
        </div>
    </div>
<% end %>

app/views/users/new.html.erb
<%= render "shared/errors", data: @user %>

<div class="ui middle aligned center aligned grid custom-center">
  <div class="custom-column column">
    <div class="ui segment">
      <h2 class="ui center aligned icon blue header">
        <i class="circular power off icon"></i>
        Sign up to MessageMe Chat App
      </h2>
      <div class="ui center aligned basic segment">
        <%= form_for(@user, url: signup_path, class: "my-form ui form", local: true) do |f| %>
          <div class="field">
            <div class="ui left input">
              <%= f.text_field :username, class: "my-input", placeholder: "Username" %>
            </div>
          </div>
          <div class="field">
            <div class="ui left input">
              <%= f.password_field :password, class: "my-input", placeholder: "Password" %>
            </div>
          </div>
          <%= f.submit "Sign Up", class: "ui primary fluid button" %>
          <%# <div class="ui divider"></div>
          <a href="#">Forgot password?</a> %>
        </div>
      </div>
      <div class="ui segment">
        Already have an account?, <a href="/login">Login</a>
      </div>
    <% end %>
  </div>
</div>